server:
  port: 8080
  servlet:
    context-path: /
#################
#  error:
#    include-message: always
#    include-binding-errors: always
#################

logging:
  level:
    org.springframework: DEBUG